const cropImageMap : { [key: string]: any } = {
    Alfalfa: require("../assets/crops/Alfafa.png"),
    Barley: require("../assets/crops/Barley.png"),
    Bermudagrass: require("../assets/crops/Bermuda Grass.png"),
    Chickpeas: require("../assets/crops/Chickpeas.png"),
    Clover: require("../assets/crops/Clover.png"),
    Corn: require("../assets/crops/Corn.png"),
    Cotton: require("../assets/crops/Cotton.png"),
    Fababeans: require("../assets/crops/Faba Beans.png"),
    Fescue: require("../assets/crops/Fescue.png"),
    Flax: require("../assets/crops/Flax.png"),
    Hay: require("../assets/crops/Hay.png"),
    Haylage: require("../assets/crops/Haylage.png"),
    Hemp: require("../assets/crops/Hemp.png"),
    Jute: require("../assets/crops/Jute.png"),
    Kenaf: require("../assets/crops/kenaf.png"),
    Lentils: require("../assets/crops/Lentils.png"),
    Lotus: require("../assets/crops/Lotus.png"),
    Lupins: require("../assets/crops/Lupins.png"),
    Maize: require("../assets/crops/Maize.png"),
    Millet: require("../assets/crops/millet.png"),
    Mungbeans: require("../assets/crops/Mung Beans.png"),
    Oats: require("../assets/crops/Oats.png"),
    Orchardgrass: require("../assets/crops/Orchardgrass.png"),
    Peanuts: require("../assets/crops/Peanuts.png"),
    Peas: require("../assets/crops/Peas.png"),
    Rice: require("../assets/crops/Rice.png"),
    Ryegrass: require("../assets/crops/Ryegrass.png"),
    Rye: require("../assets/crops/Ryegrass.png"),
    Sesame: require("../assets/crops/Sesame.png"),
    Sorghum: require("../assets/crops/Sorgum.png"),
    Soybeans: require("../assets/crops/Soybeans.png"),
    Sugarcane: require("../assets/crops/Sugarcane.png"),
    Sunflower: require("../assets/crops/Sunflower.png"),
    Sweetpotato: require("../assets/crops/Sweet Potatoe.png"),
    Teff: require("../assets/crops/Teff.png"),
    Timothyhay: require("../assets/crops/Timothy Hay.png"),
    Triticale: require("../assets/crops/Triticale.png"),
    Waterchestnut: require("../assets/crops/Water Chestnut.png"),
    Wetlandtaro: require("../assets/crops/Wetland Taro.png"),
};

const homeImageMap: { [key: string]: any } = {
	coffeeBerries: require("../assets/images/coffeeBerries.png"),
	farmerInTeaFarm: require("../assets/images/farmerInTeaFarm.png"),
	redTomatoes: require("../assets/images/redTomatoes.png"),
    grey: require("../assets/images/grey.png"),
    aibg1: require("../assets/images/aibg1.png"),
    aibg2: require("../assets/images/aibg2.jpeg"),
    aibg3: require("../assets/images/aibg3.png"),
    aibg4: require("../assets/images/aibg4.png"),
};

export { cropImageMap, homeImageMap };